workflows:
  my-workflow:
    name: driver build
    labels:
      - test
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: false
    scripts:
        - name: Build android
          script: flutter build aar --no-debug --no-profile
        - name: Build ios
          script: flutter build ios-framework --no-debug --no-profile
    artifacts:
      - build/host/outputs/repo/*
      - build/ios/framework/*
    publishing:
      email:
        recipients:
            - shinnaga.dev@gmail.com
      scripts:
        - echo 'Post-publish script a'