workflows:
  main-workflow:
    name: test workflow
    labels:
      - test
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - my-group
      vars:
        PUBLIC_ENV_VAR: $CM_BUILD_DIR/artifacts
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: false
    scripts:
        - name: env check
          script: |
            echo $CM_BRANCH
            echo $CM_TAG
            echo $CM_REPO_SLUG
