workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: '*'
          include: false
      cancel_previous_builds: true
    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"